shamefullyHoist: true

allowBuilds:
  rbxts-transform-debug: true
  rbxts-transform-env: true

overrides:
  "@rbxts/compiler-types": "$@rbxts/compiler-types"
  "@rbxts/types": "$@rbxts/types"
  "@rbxts/validate-tree": "$@rbxts/validate-tree"
  "typescript": "$typescript"
