shamefullyHoist: true

onlyBuiltDependencies:
  - "rbxts-transform-debug"
  - "rbxts-transform-env"

overrides:
  "@rbxts/compiler-types": "$@rbxts/compiler-types"
  "@rbxts/types": "$@rbxts/types"
  "@rbxts/validate-tree": "$@rbxts/validate-tree"
  "typescript": "$typescript"
