// This file is automatically @generated by Asphalt.
// It is not intended for manual editing.
declare const assets: {
	"animations/malemc/basic": string
	"animations/malemc/hurt": string
	"animations/malemc/idle": string
}

export = assets