// This file is automatically @generated by Asphalt.
// It is not intended for manual editing.
declare const assets: {
	animations: {
		malemc: {
			basic: string
			hurt: string
			idle: string
		}
	}
}

export = assets